FROM openjdk:8u171-jre

ENV SPRING_PROFILES_ACTIVE=""
ENV JAVA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"

EXPOSE 8080
EXPOSE 8000

COPY iot-main/target/iot-main.jar /iot-main.jar

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -jar /iot-main.jar" ]
