---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq
spec:
    selector:
        matchLabels:
            app: rabbitmq
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            containers:
            -   name: rabbitmq
                image: 'rabbitmq:3.7.8-management'
#                env:
#                -   name: SPRING_DATA_MONGODB_HOST
#                    value: a
#                -   name: SPRING_RABBITMQ_HOST
#                    value: a
---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
spec:
    ports:
    -   port: 5672
        name: client
    -   port: 15672 # management
        name: management
    selector:
        app: rabbitmq


---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo
spec:
    selector:
        matchLabels:
            app: mongo
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: mongo
        spec:
            containers:
            -   name: mongo
                image: 'mongo'
#                env:
#                -   name: SPRING_DATA_MONGODB_HOST
#                    value: a
#                -   name: SPRING_RABBITMQ_HOST
#                    value: a
---
apiVersion: v1
kind: Service
metadata:
    name: mongo
spec:
    ports:
    -   port: 27017
    selector:
        app: mongo


